#!/usr/bin/env python

import random
import os
import subprocess
import hashlib

os.system("clear")
m = hashlib.md5()
proc=subprocess.Popen('whoami', shell=True,stdout=subprocess.PIPE,)
output=proc.communicate()[0]
player=output.rstrip()

#print player
days = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
names = ["Joel","Fred","Mike","Leon","Kent"]
timeDirection = [" 1:00"," 4:00"," 5:00"," 6:00"," 7:00"," 8:00"," 9:00","10:00","11:00"," noon"]
phoneDigit = [1,0,9,8,7,6,5,4,3,2]
randomList = []
numToCall = []

for k in range (7):
    j = random.randint(0,9)
    randomList.append(j)

#print randomList
print("__________________________")
print("|       SCHEDULE         |")
for i in range (7):
    print "| ",days[i]," - ",names[random.randint(0,4)],timeDirection[randomList[i]],"   |"
    numToCall.append(phoneDigit[randomList[i]])
print("|________________________|")

print("               _.===========================._")
print("            .''  .-  - __- - - -- --__--- -.  ''.")
print("        __ / ,''     _|--|_________|--|_     ''. \\")
print("      /'--| ;    _.'\\ |  '         '  | /'._    ; |")
print("     //   | |_.-' .-'.'      ___      '.'-. '-._| |")
print("    (\\)   \\'' _.-' /     .-''_ ''-.     \\ '-._ ''/")
print("    (\\)    '-'    |    .' .-'' ''-. '.    |    '-'")
print("   (\\)            |   / .'(3)(2)(1)'. \\   |")
print("   (\\)            |  / / (4) .-.     \\ \\  |")
print("   (\\)            |  | |(5) (   )'==,J |  |")
print("  (\\)             |  \\ \\ (6) '-' (0) / /  |")
print(" (\\)              |   \\ '.(7)(8)(9).' /   |")
print(" (\\)           ___|    '. '-.._..-' .'    |")
print(" (\\)          /.--|      '-._____.-'      |")
print("  (\\)        (\\)  |\\_  _  __   _   __  __/|")
print(" (\\)        (\\)   |                       |")
print("(\\)_._._.__(\\)    |                       |")
print(" (\\\\\\\\\\\\\\\\\\)      '._____________________.'")
print("  '-'-'-'--'")
moo = ''.join(str(e) for e in numToCall)
#print (moo)
guess = input("What do you dial?")
#print (moo,guess)
while (str(moo) != str(guess)):
    print ("Nobody answers. Maybe you should dial someone else")
    guess = input("What do you dial?")
    
else:
#    command="echo $(whoami)phone | md5sum"
#    proc=subprocess.Popen(command, shell=True,stdout=subprocess.PIPE,)
#    output=proc.communicate()[0]
    print ("SUCCESS! After dialing the number, you hear a robotic voice saying:")
#    k = (output.rstrip())
#    k = k[:-3]
#    print k
    flag=os.popen('echo -n $(whoami)phone | md5sum').read()
    print "Here is your flag: ", flag[:-3]



